In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 1000
# mpl.rcParams['legend.fontsize'] = 15
# params = {'legend.fontsize': 20,
#           'legend.handlelength': 2}
# plot.rcParams.update(params)

In [22]:
from algorithms.moo.nsga2 import NSGA2
from constraints.as_obj import ConstraintsAsObjective
from operators.survival.rank_and_crowding.classes import (
    RankAndCrowding,
    MyConstrRankAndCrowding,
    ParallelConstrRankAndCrowding,
    MyConstrRankAndCrowding2,
)
from optimize import minimize
from visualization.scatter import Scatter
from pymoo.problems import get_problem

In [23]:
core_moea1 = NSGA2(pop_size=1000, survival=RankAndCrowding())
core_moea2 = NSGA2(pop_size=1000, survival=MyConstrRankAndCrowding())
core_moea3 = NSGA2(pop_size=1000, survival=ParallelConstrRankAndCrowding())
core_moea4 = NSGA2(pop_size=1000, survival=MyConstrRankAndCrowding2())

In [24]:
import time


def performance_timer(func):
    """
    A decorator to measure and print the execution time of a function.
    """

    def wrapper(*args, **kwargs):
        start_time = time.time()  # Capture the start time
        result = func(*args, **kwargs)  # Execute the function
        end_time = time.time()  # Capture the end time
        duration = end_time - start_time  # Calculate duration
        print(f"{func.__name__} executed in {duration:.6f} seconds")
        return result

    return wrapper


@performance_timer
def minimize_(*args, **kwargs):
    return minimize(*args, **kwargs)

In [25]:
from pymoo.indicators.gd import GD
from pymoo.indicators.gd_plus import GDPlus
from pymoo.indicators.igd import IGD
from pymoo.indicators.igd_plus import IGDPlus
from pymoo.indicators.hv import HV

metric_classes = {
    "Generational Distance (GD)": GD,
    "Generational Distance Plus (GD+)": GDPlus,
    "Inverted Generational Distance (IGD)": IGD,
    "Inverted Generational Distance Plus (IGD+)": IGDPlus,
    # "Hypervolume": HV,
}


def performance_indicators(pf, results):
    # Pre-configuration for each metric, handle special cases like HV here.
    pf_calculators = [
        (
            metric_class(ref_point=np.array([0, 0]))
            if metric_name == "Hypervolume"
            else metric_class(pf)
        )
        for metric_name, metric_class in metric_classes.items()
    ]

    def cal_acc_metric(sols):
        results_matrix = np.empty((len(sols), len(metric_classes)), dtype=object)

        for idx, sol in enumerate(sols):
            # Ensure `sol` is a 2D array with the correct shape [n_samples, n_features]
            sol = np.atleast_2d(sol)
            if sol.shape[0] == 1 and sol.shape[1] != len(pf):
                # This implies sol is a single sample with multiple features, which is the correct format
                pass
            elif sol.shape[1] == 1 and sol.shape[0] != len(pf):
                # This implies sol has the wrong orientation; it's many samples of a single feature
                sol = sol.T

            for metric_idx, calculator in enumerate(pf_calculators):
                try:
                    results_matrix[idx, metric_idx] = calculator(sol)
                except Exception as e:
                    # print(
                    #     f"Error calculating {list(metric_classes.keys())[metric_idx]}: {e}")
                    results_matrix[idx, metric_idx] = np.nan

        return [
            (np.mean(results_matrix[:, i]), np.median(results_matrix[:, i]))
            for i in range(len(pf_calculators))
        ]

    return [cal_acc_metric(rs) for rs in results]

In [26]:
from constraints.as_obj import CVRAsObjective, CDFAsObjective, CVRAsObjective2, CDFAsObjective2


@performance_timer
def compare_on(problem, n_gen=300):
    # Configuration for each optimization strategy
    configurations = [
        (problem, core_moea1, ("n_gen", n_gen), {"seed": 1, "verbose": False}),
        # (ConstraintsAsObjective(problem),
        #  core_moea1, ("n_gen", n_gen), {"seed": 1}),
        # (CVRAsObjective(problem),
        #  core_moea1, ("n_gen", n_gen), {"seed": 1}),
        # (CDFAsObjective(problem),
        #  core_moea1, ("n_gen", n_gen), {"seed": 1}),
        # (ConstraintsAsObjective(problem),
        #  core_moea2, ("n_gen", n_gen), {"seed": 1}),
        # (
        #     CVRAsObjective(problem),
        #     core_moea2,
        #     ("n_gen", n_gen),
        #     {"seed": 1, "verbose": False},
        # ),
        (
            CVRAsObjective2(problem),
            core_moea4,
            ("n_gen", n_gen),
            {"seed": 1, "verbose": False},
        ),
        # (
        #     CDFAsObjective(problem),
        #     core_moea2,
        #     ("n_gen", n_gen),
        #     {"seed": 1, "verbose": False},
        # ),
        (
            CDFAsObjective2(problem),
            core_moea4,
            ("n_gen", n_gen),
            {"seed": 1, "verbose": False},
        ),
    ]

    results = []
    for config in configurations:
        result = minimize_(*config[:-1], **config[-1])
        results.append(result)
    return results


def test(problem_name, n_gen=300, *args):
    if "dascmop" in problem_name:
        print(problem_name, args)
        problem = get_problem(problem_name, args[0])
    elif "modact" in problem_name:
        problem = get_problem(problem_name, args[0])
    else:
        print(problem_name)
        problem = get_problem(problem_name)
    pf = problem.pareto_front()
    print(
        f"Problem {problem.name}: n_var={problem.n_var} n_obj={problem.n_obj} n_ieq_constr={problem.n_ieq_constr} n_eq_constr={problem.n_eq_constr}"
    )

    results = compare_on(problem, n_gen=n_gen)

    # Check if any of the results is None
    if any(result is None for result in results):
        print("One or more optimization runs failed to return a result.")
        # Return None in place of results to indicate failure
        return pf, [None] * len(results)

    # Prepare data for performance indicators, safely handling cases where result.F might be None or incorrectly shaped
    prepared_data = []
    for i, result in enumerate(results):
        if result and hasattr(result, "F") and result.F is not None:
            # i == 0 this NGSA without additional objective
            if i > 0:
                # if i == 1 or i == 3:
                # if True:
                prepared_data.append(result.F[:, :-2])
            else:
                # prepared_data.append(result.F[:, :-1])
                prepared_data.append(result.F)
        else:
            # Use None or an appropriate placeholder if result is invalid
            print(f'algo {i} not converge')
            prepared_data.append(None)

    # Ensure all data is valid before calculating performance indicators
    if all(data is not None for data in prepared_data):
        performance_results = performance_indicators(pf, prepared_data)
        for i, metric in enumerate(metric_classes.keys()):
            print(
                f"{metric}: " +
                " | ".join(f"{perf[i]}" for perf in performance_results)
            )
    else:
        print("Performance indicators could not be calculated due to invalid data.")

    return pf, *results

# BNH


In [27]:
pf, *results = test("dascmop1", 1000, 16)
pf, results[0].F, results[1].F, results[2].F

dascmop1 (16,)
Problem <bound method Problem.name of <pymoo.problems.multi.dascmop.DASCMOP1 object at 0x7c1662ec6ad0>>: n_var=30 n_obj=2 n_ieq_constr=11 n_eq_constr=0
minimize_ executed in 101.832141 seconds
minimize_ executed in 104.066108 seconds
minimize_ executed in 96.817233 seconds
compare_on executed in 302.715875 seconds
algo 0 not converge
algo 1 not converge
algo 2 not converge
Performance indicators could not be calculated due to invalid data.


(array([[0.5       , 1.5       ],
        [0.501001  , 1.499999  ],
        [0.502002  , 1.499996  ],
        [0.503003  , 1.499991  ],
        [0.504004  , 1.499984  ],
        [0.50500501, 1.4999749 ],
        [0.50600601, 1.4999639 ],
        [0.50700701, 1.4999509 ],
        [0.50800801, 1.4999359 ],
        [0.50900901, 1.4999188 ],
        [0.51001001, 1.4998998 ],
        [0.51101101, 1.4998788 ],
        [0.51201201, 1.4998557 ],
        [0.51301301, 1.4998307 ],
        [0.51401401, 1.4998036 ],
        [0.51501502, 1.4997745 ],
        [0.51601602, 1.4997435 ],
        [0.51701702, 1.4997104 ],
        [0.51801802, 1.4996754 ],
        [0.51901902, 1.4996383 ],
        [0.52002002, 1.4995992 ],
        [0.52102102, 1.4995581 ],
        [0.52202202, 1.499515  ],
        [0.52302302, 1.4994699 ],
        [0.52402402, 1.4994228 ],
        [0.52502503, 1.4993737 ],
        [0.52602603, 1.4993226 ],
        [0.52702703, 1.4992695 ],
        [0.52802803, 1.4992144 ],
        [0.529

In [28]:
pf, *results = test("dascmop2", 1000, 16)
pf, results[0].F, results[1].F, results[2].F

dascmop2 (16,)
Problem <bound method Problem.name of <pymoo.problems.multi.dascmop.DASCMOP2 object at 0x7c166323cfa0>>: n_var=30 n_obj=2 n_ieq_constr=11 n_eq_constr=0
minimize_ executed in 123.697541 seconds
minimize_ executed in 109.284381 seconds
minimize_ executed in 96.467283 seconds
compare_on executed in 329.449517 seconds
algo 2 not converge
Performance indicators could not be calculated due to invalid data.


(array([[0.5       , 1.5       ],
        [0.501001  , 1.4683614 ],
        [0.502002  , 1.4552563 ],
        ...,
        [1.4489489 , 0.52585989],
        [1.4499499 , 0.52534624],
        [1.5       , 0.5       ]]),
 array([[0.83839984, 0.91837828],
        [0.80207923, 0.9503406 ],
        [0.80546628, 0.94723174],
        ...,
        [0.8371347 , 0.91918969],
        [0.83081073, 0.92465375],
        [0.83407032, 0.92182686]]),
 array([[0.80398512, 0.94848886, 0.        , 0.        ],
        [0.80883469, 0.94408968, 0.        , 0.        ],
        [0.80618372, 0.94649752, 0.        , 0.        ],
        ...,
        [0.83198802, 0.92376359, 0.        , 0.        ],
        [0.80406343, 0.94843667, 0.        , 0.        ],
        [0.80457797, 0.94793957, 0.        , 0.        ]]),
 None)

In [30]:
pf, *results = test("dascmop3", 500, 16)
pf, results[0].F, results[1].F, results[2].F

dascmop3 (16,)
Problem <bound method Problem.name of <pymoo.problems.multi.dascmop.DASCMOP3 object at 0x7c1663459840>>: n_var=30 n_obj=2 n_ieq_constr=11 n_eq_constr=0
minimize_ executed in 54.205597 seconds
minimize_ executed in 53.474943 seconds
minimize_ executed in 47.532207 seconds
compare_on executed in 155.213127 seconds
algo 2 not converge
Performance indicators could not be calculated due to invalid data.


(array([[0.5       , 1.5       ],
        [0.501001  , 1.4762229 ],
        [0.502002  , 1.4709774 ],
        [0.503003  , 1.4687771 ],
        [0.504004  , 1.4681494 ],
        [0.65015015, 1.4652264 ],
        [0.7002002 , 1.054135  ],
        [0.9044044 , 0.89863654],
        [1.1066066 , 0.77294554],
        [1.3008008 , 0.61141457],
        [1.5       , 0.5       ]]),
 array([[0.84946302, 1.26547234],
        [0.84981388, 1.26355107],
        [0.84995667, 1.26217475],
        [0.90389637, 0.89561829]]),
 array([[0.8495091 , 1.26443892, 0.        , 0.        ],
        [0.84938013, 1.26533869, 0.        , 0.        ],
        [0.90387847, 0.89553342, 0.        , 0.        ]]),
 None)

In [29]:
pf, *results = test("dascmop4", 500, 16)
pf, results[0].F, results[1].F, results[2].F

dascmop4 (16,)
Problem <bound method Problem.name of <pymoo.problems.multi.dascmop.DASCMOP4 object at 0x7c1663462b30>>: n_var=30 n_obj=2 n_ieq_constr=11 n_eq_constr=0
minimize_ executed in 52.581327 seconds
minimize_ executed in 52.821261 seconds
minimize_ executed in 46.190309 seconds
compare_on executed in 151.593217 seconds
algo 2 not converge
Performance indicators could not be calculated due to invalid data.


(array([[0.5       , 1.5       ],
        [0.501001  , 1.499999  ],
        [0.502002  , 1.499996  ],
        [0.503003  , 1.499991  ],
        [0.504004  , 1.499984  ],
        [0.50500501, 1.4999749 ],
        [0.50600601, 1.4999639 ],
        [0.50700701, 1.4999509 ],
        [0.50800801, 1.4999359 ],
        [0.50900901, 1.4999188 ],
        [0.51001001, 1.4998998 ],
        [0.51101101, 1.4998788 ],
        [0.51201201, 1.4998557 ],
        [0.51301301, 1.4998307 ],
        [0.51401401, 1.4998036 ],
        [0.51501502, 1.4997745 ],
        [0.51601602, 1.4997435 ],
        [0.51701702, 1.4997104 ],
        [0.51801802, 1.4996754 ],
        [0.51901902, 1.4996383 ],
        [0.52002002, 1.4995992 ],
        [0.52102102, 1.4995581 ],
        [0.52202202, 1.499515  ],
        [0.52302302, 1.4994699 ],
        [0.52402402, 1.4994228 ],
        [0.52502503, 1.4993737 ],
        [0.52602603, 1.4993226 ],
        [0.52702703, 1.4992695 ],
        [0.52802803, 1.4992144 ],
        [0.529

In [17]:
pf, *results = test("dascmop5", 200, 16)
pf, results[0].F, results[1].F, results[2].F

dascmop5 (16,)
Problem <bound method Problem.name of <pymoo.problems.multi.dascmop.DASCMOP5 object at 0x7c1662d5e290>>: n_var=30 n_obj=2 n_ieq_constr=11 n_eq_constr=0
minimize_ executed in 8.794743 seconds
minimize_ executed in 8.042573 seconds
minimize_ executed in 7.686258 seconds
compare_on executed in 24.523950 seconds
algo 1 not converge
algo 2 not converge
Performance indicators could not be calculated due to invalid data.


(array([[0.5       , 1.5       ],
        [0.501001  , 1.4683614 ],
        [0.502002  , 1.4552563 ],
        [0.503003  , 1.4452003 ],
        [0.504004  , 1.4367228 ],
        [0.50500501, 1.4292539 ],
        [0.50600601, 1.4225016 ],
        [0.50700701, 1.4162921 ],
        [0.50800801, 1.4105125 ],
        [0.50900901, 1.4050842 ],
        [0.51001001, 1.39995   ],
        [0.51101101, 1.3950666 ],
        [0.51201201, 1.3904007 ],
        [0.51301301, 1.3859254 ],
        [0.51401401, 1.3816192 ],
        [0.51501502, 1.3774642 ],
        [0.51601602, 1.3734456 ],
        [0.51701702, 1.3695507 ],
        [0.51801802, 1.3657688 ],
        [0.51901902, 1.3620905 ],
        [0.52002002, 1.3585079 ],
        [0.52102102, 1.3550137 ],
        [0.52202202, 1.3516018 ],
        [0.52302302, 1.3482666 ],
        [0.52402402, 1.3450031 ],
        [0.52502503, 1.341807  ],
        [0.52602603, 1.3386742 ],
        [0.52702703, 1.335601  ],
        [0.52802803, 1.3325843 ],
        [0.529

In [16]:
pf, *results = test("dascmop6", 500, 16)
pf, results[0].F, results[1].F, results[2].F

dascmop6 (16,)
Problem <bound method Problem.name of <pymoo.problems.multi.dascmop.DASCMOP6 object at 0x7c1663427f40>>: n_var=30 n_obj=2 n_ieq_constr=11 n_eq_constr=0
minimize_ executed in 7.943926 seconds
minimize_ executed in 8.099066 seconds
minimize_ executed in 8.052566 seconds
compare_on executed in 24.095895 seconds
algo 1 not converge
algo 2 not converge
Performance indicators could not be calculated due to invalid data.


(array([[0.5       , 1.5       ],
        [0.501001  , 1.4762229 ],
        [0.502002  , 1.4709774 ],
        [0.503003  , 1.4687771 ],
        [0.504004  , 1.4681494 ],
        [0.65015015, 1.4652264 ],
        [0.7002002 , 1.054135  ],
        [0.9044044 , 0.89863654],
        [1.1066066 , 0.77294554],
        [1.3008008 , 0.61141457],
        [1.5       , 0.5       ]]),
 array([[0.50159012, 1.47259605],
        [0.50247126, 1.46952118],
        [0.50135453, 1.47344314],
        [0.50284316, 1.46880979],
        [0.50342231, 1.46820125],
        [0.50113907, 1.47459644],
        [0.50339919, 1.46823783],
        [0.50310499, 1.46854207],
        [0.50219837, 1.47036095],
        [0.50085974, 1.47710368],
        [0.50209312, 1.4705986 ],
        [0.50233524, 1.47021586],
        [0.50125172, 1.47401204],
        [0.50396646, 1.46819546],
        [0.50236109, 1.46989519]]),
 None,
 None)

In [18]:
pf, *results = test("dascmop7", 500, 16)
pf, results[0].F, results[1].F, results[2].F

dascmop7 (16,)
Problem <bound method Problem.name of <pymoo.problems.multi.dascmop.DASCMOP7 object at 0x7c1663458850>>: n_var=30 n_obj=3 n_ieq_constr=7 n_eq_constr=0
minimize_ executed in 23.231211 seconds
minimize_ executed in 22.582301 seconds
minimize_ executed in 19.719371 seconds
compare_on executed in 65.533279 seconds
algo 2 not converge
Performance indicators could not be calculated due to invalid data.


(array([[0.5       , 0.5       , 1.5       ],
        [0.5       , 0.51010101, 1.489899  ],
        [0.5       , 0.52020202, 1.479798  ],
        ...,
        [1.479798  , 0.5       , 0.52020202],
        [1.489899  , 0.5       , 0.51010101],
        [1.5       , 0.5       , 0.5       ]]),
 array([[0.49995151, 0.58086338, 1.41894739],
        [0.5007725 , 0.81480673, 1.18433891],
        [0.50456278, 0.81307626, 1.18229661],
        ...,
        [0.50159884, 0.71030093, 1.28800145],
        [0.50635354, 0.68167909, 1.31203756],
        [0.50513362, 0.67656283, 1.31806582]]),
 array([[0.66661083, 0.74562207, 1.08756818, 0.        , 0.        ],
        [0.52944837, 0.56810277, 1.40261273, 0.        , 0.        ],
        [0.65310024, 0.85652203, 0.99061048, 0.        , 0.        ],
        ...,
        [0.587492  , 0.68751322, 1.22471035, 0.        , 0.        ],
        [0.59359367, 0.71595674, 1.19033   , 0.        , 0.        ],
        [0.59083845, 0.69534691, 1.21377543, 0.        

In [15]:
pf, *results = test("dascmop8", 500, 16)
pf, results[0].F, results[1].F, results[2].F

dascmop8 (16,)
Problem <bound method Problem.name of <pymoo.problems.multi.dascmop.DASCMOP8 object at 0x7c1662ec6e30>>: n_var=30 n_obj=3 n_ieq_constr=7 n_eq_constr=0
minimize_ executed in 22.764735 seconds
minimize_ executed in 20.023026 seconds
minimize_ executed in 18.035995 seconds
compare_on executed in 60.824070 seconds
algo 2 not converge
Performance indicators could not be calculated due to invalid data.


(array([[1.5       , 0.5       , 0.5       ],
        [1.4998741 , 0.51586596, 0.5       ],
        [1.4994965 , 0.53172793, 0.5       ],
        ...,
        [0.5       , 0.5       , 1.5       ],
        [0.5       , 0.5       , 1.5       ],
        [0.5       , 0.5       , 1.5       ]]),
 array([[1.06810486, 1.32279854, 0.4999094 ],
        [0.52357156, 0.57481521, 1.49682934],
        [1.1868545 , 0.50004091, 1.2266078 ],
        ...,
        [0.87353104, 1.29932517, 0.97038028],
        [0.83365749, 1.1187738 , 1.21101256],
        [1.14304829, 1.1100606 , 0.96259958]]),
 array([[0.62162905, 1.27212581, 1.12387417, 0.        , 0.        ],
        [0.64061487, 1.48925787, 0.54023881, 0.        , 0.        ],
        [1.14848293, 1.19105897, 0.81972021, 0.        , 0.        ],
        ...,
        [0.78358991, 1.3898219 , 0.85742807, 0.        , 0.        ],
        [0.78555983, 1.40179843, 0.82478093, 0.        , 0.        ],
        [0.78279023, 1.38952551, 0.85862906, 0.        

In [10]:
pf, *results = test("dascmop9", 200, 16)
pf, results[0].F, results[1].F, results[2].F

dascmop9 (16,)
Problem <bound method Problem.name of <pymoo.problems.multi.dascmop.DASCMOP9 object at 0x7c16627bc640>>: n_var=30 n_obj=3 n_ieq_constr=7 n_eq_constr=0
minimize_ executed in 9.033986 seconds
minimize_ executed in 8.722351 seconds
minimize_ executed in 7.376199 seconds
compare_on executed in 25.133273 seconds
Generational Distance (GD): (0.004947633293754378, 0.0054698433863406525) | (0.0042463874864052936, 0.004147832316327425) | (0.004859143721842364, 0.005501264086089613)
Generational Distance Plus (GD+): (0.0018026241073649646, 0.0015411835873532231) | (0.0019302737566316743, 0.0014922795783554044) | (0.002137501491416426, 0.0019528041964639309)
Inverted Generational Distance (IGD): (0.651082283646549, 0.6504151231599302) | (0.6447669253080689, 0.6440995705825114) | (0.6460264465224134, 0.6440264601096894)
Inverted Generational Distance Plus (IGD+): (0.40403651503786725, 0.40306847633613463) | (0.4054698298159435, 0.40321024470517786) | (0.4034535415899421, 0.402992218

(array([[1.5       , 0.5       , 0.5       ],
        [1.4998741 , 0.51586596, 0.5       ],
        [1.4994965 , 0.53172793, 0.5       ],
        ...,
        [0.5       , 0.5       , 1.5       ],
        [0.5       , 0.5       , 1.5       ],
        [0.5       , 0.5       , 1.5       ]]),
 array([[0.54789907, 0.80337469, 1.45165181],
        [0.53673427, 0.60448135, 1.49378019],
        [0.55207257, 0.92922831, 1.40154131],
        [0.55106387, 0.75970233, 1.46445316],
        [0.5797886 , 0.92151174, 1.4031889 ],
        [0.5706621 , 0.60345733, 1.49205112],
        [0.55486002, 0.79123637, 1.45510142],
        [0.54784103, 0.78240899, 1.45803723],
        [0.54665205, 0.78359409, 1.45769313],
        [0.52748518, 0.64461408, 1.48921021],
        [0.56226309, 0.59227588, 1.49370301],
        [0.54881871, 0.76651855, 1.46261582],
        [0.5843784 , 0.94337569, 1.39226734],
        [0.54768415, 0.78246138, 1.45805934],
        [0.54796773, 0.76837097, 1.46200542],
        [0.56683667

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
# plot.add(results[0].F, marker="x", color="red", label="Original CMOP + NSGA-II")
plot.add(results[0].F[:, :-1], marker="d", color="yellow", label="UMOP + Baseline")
# plot.add(results[2].F[:, :-1], marker="+",
        #  color="green", label="UMOP + Baseline + Our CDP")
plot.add(
    results[1].F[:, :-1], marker="1", color="blue", label="UMOP + Our generalized framework"
)
plot.add(results[2].F[:, :-1], marker="2",
         color="purple", label="UMOP + Our framework + CDF")
plot.show()

# SRN

In [ ]:
pf, *results = test("srn", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
# plot.add(results[0].F, marker="x", color="red", label="Original CMOP + NSGA-II")
plot.add(results[0].F[:, :-1], marker="d", color="yellow", label="UMOP + Baseline")
# plot.add(results[2].F[:, :-1], marker="+",
        #  color="green", label="UMOP + Baseline + Our CDP")
plot.add(
    results[1].F[:, :-1], marker="1", color="blue", label="UMOP + Our generalized framework"
)
plot.add(results[2].F[:, :-1], marker="2",
         color="purple", label="UMOP + Our framework + CDF")
plot.show()

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange")
plot.add(results[0].F, marker="x", color="red")
plot.add(results[1].F[results[1].F[:, -1] == 0][:, :-1], marker="d", color="yellow")
plot.add(results[2].F[:, :-1], marker="+",
         color="green")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue"
)
plot.add(results[4].F[:, :-1], marker="2",
         color="purple")
plot.show()

# ZDT


In [ ]:
# problem_zdt1 = get_problem("zdt1")
# problem = problem_zdt1
# print(
#     f"Problem {problem.name}: n_var={problem.n_var} n_obj={problem.n_obj} n_ieq_constr={problem.n_ieq_constr} n_eq_constr={problem.n_eq_constr}"
# )

# res0, res1, res2, res3 = compare_on(problem)
# print(
#     f"F1-F2: {sum(res1.F - res2.F)}   F2-F3{sum(res2.F - res3.F)}   F1-F3{sum(res1.F - res3.F)}"
# )

# plot = Scatter()
# plot.add(problem.pareto_front(), marker="*", color="orange", label="Pareto front")
# plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline CV_as_obj")
# plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our CV_as_obj")
# plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our CV_as_obj")
# plot.show()

In [ ]:
# problem_zdt2 = get_problem("zdt2")

# res0, res1, res2, res3 = compare_on(problem_zdt2)

# plot = Scatter()
# plot.add(problem_zdt2.pareto_front(), marker="*", color="orange", label="Pareto front")
# plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline CV_as_obj")
# plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our CV_as_obj")
# plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our CV_as_obj")
# plot.show()

In [ ]:
# problem_zdt3 = get_problem("zdt3")

# res0, res1, res2, res3 = compare_on(problem_zdt3)

# plot = Scatter()
# plot.add(problem_zdt3.pareto_front(), marker="*", color="orange", label="Pareto front")
# plot.add(res0.Fa, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline CV_as_obj")
# plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our CV_as_obj")
# plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our CV_as_obj")
# plot.show()

In [ ]:
# problem_zdt4 = get_problem("zdt4")

# res0, res1, res2, res3 = compare_on(problem_zdt4)
# print(
#     f"F1-F2: {sum(res1.F - res2.F)}   F2-F3{sum(res2.F - res3.F)}   F1-F3{sum(res1.F - res3.F)}"
# )

# plot = Scatter()
# plot.add(problem_zdt4.pareto_front(), marker="*", color="orange", label="Pareto front")
# plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline CV_as_obj")
# plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our CV_as_obj")
# plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our CV_as_obj")
# plot.show()

In [ ]:
# problem_zdt5 = get_problem("zdt5", normalize=False)

# res0, res1, res2, res3 = compare_on(problem_zdt5, n_gen=3000)
# print(
#     f"F1-F2: {sum(res1.F - res2.F)}   F2-F3{sum(res2.F - res3.F)}   F1-F3{sum(res1.F - res3.F)}"
# )

# plot = Scatter()
# plot.add(problem_zdt5.pareto_front(), marker="*", color="orange", label="Pareto front")
# plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline CV_as_obj")
# plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our CV_as_obj")
# plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our CV_as_obj")
# plot.show()

In [ ]:
# problem_zdt6 = get_problem("zdt6")

# res0, res1, res2, res3 = compare_on(problem_zdt6)
# print(
#     f"F1-F2: {sum(res1.F - res2.F)}   F2-F3{sum(res2.F - res3.F)}   F1-F3{sum(res1.F - res3.F)}"
# )

# plot = Scatter()
# plot.add(problem_zdt6.pareto_front(), marker="*", color="orange", label="Pareto front")
# plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline CV_as_obj")
# plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our CV_as_obj")
# plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our CV_as_obj")
# plot.show()

In [ ]:
# cv = res3.F[:, 0]
# least_infeas = cv.argmin()
# x = res3.X[least_infeas]

# sol = Individual(X=x)
# Evaluator().eval(problem2, sol)

# print("Best solution found: \nX = %s\nF = %s\nCV = %s" % (sol.X, sol.F, sol.CV))

In [ ]:
# plot = Scatter()
# plot.add(problem2.pareto_front(), marker="*", color="black", alpha=0.7, s=100)
# plot.add(res3.F[:,1:], facecolor="none", edgecolor="red")
# plot.show()

In [ ]:
# X, F = res3.opt.get("X", "F")
# hist = res3.history
# print(len(hist))

In [ ]:
# n_evals = []             # corresponding number of function evaluations\
# hist_F = []              # the objective space values in each generation
# hist_cv = []             # constraint violation in each generation
# hist_cv_avg = []         # average constraint violation in the whole population

# for algo in hist:

#     # store the number of function evaluations
#     n_evals.append(algo.evaluator.n_eval)

#     # retrieve the optimum from the algorithm
#     opt = algo.opt

#     # store the least contraint violation and the average in each population
#     hist_cv.append(opt.get("CV").min())
#     hist_cv_avg.append(algo.pop.get("CV").mean())

#     # filter out only the feasible and append and objective space values
#     feas = np.where(opt.get("feasible"))[0]
#     hist_F.append(opt.get("F")[feas])

In [ ]:
# k = np.where(np.array(hist_cv) <= 0.0)[0].min()
# print(f"At least one feasible solution in Generation {k} after {n_evals[k]} evaluations.")

In [ ]:
# # replace this line by `hist_cv` if you like to analyze the least feasible optimal solution and not the population
# vals = hist_cv_avg

# k = np.where(np.array(vals) <= 0.0)[0].min()
# print(f"Whole population feasible in Generation {k} after {n_evals[k]} evaluations.")

# plt.figure(figsize=(7, 5))
# plt.plot(n_evals, vals,  color='black', lw=0.7, label="Avg. CV of Pop")
# plt.scatter(n_evals, vals,  facecolor="none", edgecolor='black', marker="p")
# plt.axvline(n_evals[k], color="red", label="All Feasible", linestyle="--")
# plt.title("Convergence")
# plt.xlabel("Function Evaluations")
# plt.ylabel("Hypervolume")
# plt.legend()
# plt.show()

In [ ]:
# approx_ideal = F[:,-2:].min(axis=0)
# approx_nadir = F[:,-2:].max(axis=0)
# approx_ideal, approx_nadir

In [ ]:
# from pymoo.indicators.hv import Hypervolume

# metric = Hypervolume(ref_point=np.array([0.1, 0.1]),
#                      norm_ref_point=False,
#                      zero_to_one=True,
#                      ideal=approx_ideal,
#                      nadir=approx_nadir)

# hv = [metric.do(_F[:, -2:]) for _F in hist_F]

# plt.figure(figsize=(7, 5))
# plt.plot(n_evals, hv, color='black', lw=0.7, label="Avg. CV of Pop")
# plt.scatter(n_evals, hv, facecolor="none", edgecolor='black', marker="p")
# plt.title("Convergence")
# plt.xlabel("Function Evaluations")
# plt.ylabel("Hypervolume")
# plt.show()

In [ ]:
# from pymoo.util.running_metric import RunningMetricAnimation

# running = RunningMetricAnimation(delta_gen=5,
#                         n_plots=3,
#                         key_press=False,
#                         do_show=True)

# for algorithm in res3.history[:50]:
#     running.update(algorithm)

In [ ]:
# from pymoo.indicators.igd import IGD

# metric = IGD(pf, zero_to_one=True)

# igd = [metric.do(_F) for _F in hist_F]

# plt.plot(n_evals, igd,  color='black', lw=0.7, label="Avg. CV of Pop")
# plt.scatter(n_evals, igd,  facecolor="none", edgecolor='black', marker="p")
# plt.axhline(10**-2, color="red", label="10^-2", linestyle="--")
# plt.title("Convergence")
# plt.xlabel("Function Evaluations")
# plt.ylabel("IGD")
# plt.yscale("log")
# plt.legend()
# plt.show()

# OSY


In [ ]:
pf, *results = test("osy", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange")
plot.add(results[0].F, marker="x", color="red")
plot.add(results[1].F[results[1].F[:, -1] == 0][:, :-1], marker="d", color="yellow")
plot.add(results[2].F[:, :-1], marker="+",
         color="green")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue"
)
plot.add(results[4].F[:, :-1], marker="2",
         color="purple")
plot.show()

# TNK


In [ ]:
pf, *results = test("tnk", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
# plot.add(results[0].F, marker="x", color="red", label="Original CMOP + NSGA-II")
plot.add(results[0].F[:, :-1], marker="d", color="yellow", label="UMOP + Baseline")
# plot.add(results[2].F[:, :-1], marker="+",
        #  color="green", label="UMOP + Baseline + Our CDP")
plot.add(
    results[1].F[:, :-1], marker="1", color="blue", label="UMOP + Our generalized framework"
)
plot.add(results[2].F[:, :-1], marker="2",
         color="purple", label="UMOP + Our framework + CDF")
plot.show()

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange")
plot.add(results[0].F, marker="x", color="red")
plot.add(results[1].F[results[1].F[:, -1] == 0][:, :-1], marker="d", color="yellow")
plot.add(results[2].F[:, :-1], marker="+",
         color="green")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue"
)
plot.add(results[4].F[:, :-1], marker="2",
         color="purple")
plot.show()

In [ ]:
# plt.hist(res1.F[:, -1:], bins=30, color="green", alpha=0.7, label="Sum CV_as_obj")
# plt.hist(res2.F[:, -1:], bins=30, color="blue", alpha=0.7, label="Max CV_as_obj")
# plt.hist(res3.F[:, -1:], bins=30, color="purple", alpha=0.7, label="Median CV_as_obj")

# Add labels and title
# plt.xlabel("Values")
# plt.ylabel("Frequency")
# plt.title("Histogram of CV")

# Add a legend
# plt.legend()

# Show the plot
# plt.show()

# Carside


In [ ]:
pf, *results = test("Carside", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
# plot.add(results[0].F, marker="x", color="red", label="Original CMOP + NSGA-II")
plot.add(results[0].F[results[0].F[:, -1] == 0][:, :-1], marker="d", color="yellow", label="UMOP + Baseline")
# plot.add(results[2].F[:, :-1], marker="+",
        #  color="green", label="UMOP + Baseline + Our CDP")
plot.add(
    results[1].F[results[1].F[:, -1] == 0][:, :-1], marker="1", color="blue", label="UMOP + Our generalized framework"
)
plot.add(results[2].F[results[2].F[:, -1] == 0][:, :-1], marker="2",
         color="purple", label="UMOP + Our framework + CDF")
plot.show()

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Original CMOP + NSGA-II")
plot.add(results[1].F[results[1].F[:, -1] == 0][:, :-1], marker="d", color="yellow", label="UMOP + Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="UMOP + Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="UMOP + Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="2",
         color="purple", label="UMOP + Our framework + CDF")
plot.show()

In [ ]:
plot = Scatter(tight_layout=True)
# plot.add(results[1].F, marker="+", color="green", label="Baseline")
plot.add(results[2].F, marker=".", color="green", label="Baseline + Our CDP")
plot.add(results[3].F, marker="1", color="blue",
         label="Our generalized framework")
plot.add(results[4].F, marker="1", color="purple", label="Our framework + CDF")
plot.show()

# Pressure Vessel


In [ ]:
pf, *results = test("pressure_vessel", n_gen=300)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

# G


## G1


In [ ]:
pf, *results = test("g1", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
plot.add(results[1].F[results[1].F[:, -1] == 0][:, :-1], marker="D", color="Yellow", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

## G2


In [ ]:
pf, *results = test("g1", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange")
plot.add(results[0].F, marker="x", color="red")
plot.add(results[1].F[results[1].F[:, -1] == 0][:, :-1], marker="D", color="yellow")
plot.add(results[2].F[:, :-1], marker="+",
         color="green")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple")
plot.show()

## G3 (1 Constraint)


In [ ]:
# pf, res0, res1, res2, res3 = test("g3", n_gen=300)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our generalized framework")
plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our framework + CDF")
plot.show()

## G4


In [ ]:
pf, res0, res1, res2, res3 = test("g4", n_gen=300)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(res0.F, marker="x", color="red", label="Death penalty")
plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our generalized framework")
plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our framework + CDF")
plot.show()

## G5


In [ ]:
pf, res0, res1, res2, res3 = test("g5", n_gen=300)

In [ ]:
pf

In [ ]:
res0.F

In [ ]:
res2.F

In [ ]:
res3.F

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our generalized framework")
plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our framework + CDF")
plot.show()

## G6


In [ ]:
pf, res0, res1, res2, res3 = test("g6", n_gen=300)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our generalized framework")
plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our framework + CDF")
plot.show()

## G7


In [ ]:
pf, res0, res1, res2, res3 = test("g7", n_gen=300)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our generalized framework")
plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our framework + CDF")
plot.show()

## G8


In [ ]:
pf, res0, res1, res2, res3 = test("g8", n_gen=300)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our generalized framework")
plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our framework + CDF")
plot.show()

## G9


In [ ]:
pf, res0, res1, res2, res3 = test("g9", n_gen=300)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our generalized framework")
plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our framework + CDF")
plot.show()

## G10


In [ ]:
pf, res0, res1, res2, res3 = test("g10", n_gen=300)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our generalized framework")
plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our framework + CDF")
plot.show()

## G11


In [ ]:
pf, res0, res1, res2, res3 = test("g11", n_gen=300)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our generalized framework")
plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our framework + CDF")
plot.show()

## G12


In [ ]:
pf, res0, res1, res2, res3 = test("g12", n_gen=300)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our generalized framework")
plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our framework + CDF")
plot.show()

## G13


In [ ]:
pf, res0, res1, res2, res3 = test("g13", n_gen=300)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our generalized framework")
plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our framework + CDF")
plot.show()

## G14


In [ ]:
pf, res0, res1, res2, res3 = test("g14", n_gen=300)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(res0.F, marker="x", color="red", label="Death penalty")
# plot.add(res1.F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(res2.F[:, :-1], marker="1", color="blue", label="Our generalized framework")
plot.add(res3.F[:, :-1], marker="1", color="purple", label="Our framework + CDF")
plot.show()

# MW


## MW1 (1 constraint)


In [ ]:
pf, *results = test("mw", n_gen=300)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

## MW2


In [ ]:
pf, *results = test("mw2", n_gen=100)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

## MW3


In [ ]:
pf, *results = test("mw3", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

## MW4 (1 constraint)


In [ ]:
pf, *results = test("mw4", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

## MW5


In [ ]:
pf, *results = test("mw5", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

## MW6 (1 constraint)


In [ ]:
pf, *results = test("mw6", n_gen=100)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

## MW7


In [ ]:
pf, *results = test("mw7", n_gen=100)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

## MW8 (1 constraint)


In [ ]:
pf, *results = test("mw8", n_gen=100)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

## MW9


In [ ]:
pf, *results = test("mw9", n_gen=100)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

## MW10


In [ ]:
pf, *results = test("mw13", n_gen=15)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

## MW14 (1 constraint)


In [ ]:
pf, *results = test("mw14", n_gen=100)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
# plot.add(results[3].F[:, :-1], marker="1", color="blue",
#          label="Our generalized framework")
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

# DAS-CMOP


## DAS-CMOP-1


In [ ]:
pf, *results = test("dascmop1", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

In [ ]:
pf, *results = test("dascmop2", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

In [ ]:
pf, *results = test("dascmop3", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

In [ ]:
pf, *results = test("dascmop4", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

In [ ]:
pf, *results = test("dascmop5", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

In [ ]:
pf, *results = test("dascmop6", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

In [ ]:
pf, *results = test("dascmop7", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

In [ ]:
pf, *results = test("dascmop8", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

In [ ]:
pf, *results = test("dascmop9", n_gen=500)

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

# MODAct


In [ ]:
pf, *results = test("modact", 10, "cs1")

In [ ]:
plot = Scatter()
plot.add(pf, marker="*", color="orange", label="Pareto front")
plot.add(results[0].F, marker="x", color="red", label="Death penalty")
# plot.add(results[1].F[:, :-1], marker="+", color="green", label="Baseline")
plot.add(results[2].F[:, :-1], marker="+",
         color="green", label="Baseline + Our CDP")
plot.add(
    results[3].F[:, :-1], marker="1", color="blue", label="Our generalized framework"
)
plot.add(results[4].F[:, :-1], marker="1",
         color="purple", label="Our framework + CDF")
plot.show()

In [ ]:
terminate_here

# To_excel


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from constraints.as_obj import CVRAsObjective, CDFAsObjective

POP_SIZE = 500
N_GEN = 300

core_moea1 = NSGA2(pop_size=POP_SIZE, survival=RankAndCrowding())
core_moea2 = NSGA2(pop_size=POP_SIZE, survival=MyConstrRankAndCrowding())
core_moea3 = NSGA2(pop_size=POP_SIZE, survival=ParallelConstrRankAndCrowding())


@performance_timer
def compare_on(problem, n_gen=300):
    # Configuration for each optimization strategy
    configurations = [
        # (problem, core_moea1, ("n_gen", n_gen), {"seed": 1, "verbose": False}),
        (ConstraintsAsObjective(problem),
         core_moea1, ("n_gen", n_gen), {"seed": 1}),
        (CVRAsObjective(problem),
         core_moea1, ("n_gen", n_gen), {"seed": 1}),
        (CDFAsObjective(problem),
         core_moea1, ("n_gen", n_gen), {"seed": 1}),
        # (ConstraintsAsObjective(problem),
        #  core_moea2, ("n_gen", n_gen), {"seed": 1}),
        # (
        #     CVRAsObjective(problem),
        #     core_moea2,
        #     ("n_gen", n_gen),
        #     {"seed": 1, "verbose": False},
        # ),
        # (
        #     CDFAsObjective(problem),
        #     core_moea2,
        #     ("n_gen", n_gen),
        #     {"seed": 1, "verbose": False},
        # ),
    ]

    results = []
    for config in configurations:
        result = minimize_(*config[:-1], **config[-1])
        results.append(result)
    return results


def test(problem_name, n_gen=300, **kwargs):
    if "dascmop" in problem_name or "modact" in problem_name:
        if 'additional_args' in kwargs:
            problem = get_problem(problem_name, kwargs['additional_args'])
        else:
            raise ValueError(
                f"Additional arguments required for problem {problem_name}")
    else:
        problem = get_problem(problem_name)
    pf = problem.pareto_front()
    print(f"Problem {problem.name}: n_var={problem.n_var} n_obj={problem.n_obj} n_ieq_constr={problem.n_ieq_constr} n_eq_constr={problem.n_eq_constr}")

    results = compare_on(problem, n_gen=n_gen)

    # Check if any of the results is None
    if any(result is None for result in results):
        print("One or more optimization runs failed to return a result.")
        return pf, [None]*len(results)

    # Prepare data for performance indicators
    prepared_data = []
    for i, result in enumerate(results):
        if result and hasattr(result, 'F') and result.F is not None:
            # if i > 0:
            if True:
                prepared_data.append(result.F[:, :-1])
            else:
                prepared_data.append(result.F)
        else:
            prepared_data.append(None)

    # Ensure all data is valid before calculating performance indicators
    if all(data is not None for data in prepared_data):
        performance_results = performance_indicators(pf, prepared_data)
        for i, metric in enumerate(metric_classes.keys()):
            print(f"{metric}: " +
                  " | ".join(f"{perf[i]}" for perf in performance_results))
    else:
        print("Performance indicators could not be calculated due to invalid data.")

    return pf, results


def create_charts(df, output_dir='.'):
    metrics = df['Metric'].unique()
    problems = df['Problem'].unique()

    for problem in problems:
        problem_df = df[df['Problem'] == problem]
        for metric in metrics:
            metric_df = problem_df[problem_df['Metric'] == metric]
            plt.figure(figsize=(10, 6))
            plt.bar(metric_df['Algorithm'],
                    metric_df['GD+ Mean'], yerr=metric_df['GD+ Median'])
            plt.title(f'{metric} for {problem}')
            plt.xlabel('Algorithm')
            plt.ylabel(metric)
            plt.savefig(f'{output_dir}/{problem}_{metric}.png')
            plt.close()

# Function to compare multiple problems and export results to Excel


def compare_problems_to_excel(problem_configs, n_gen=300, output_file='results.xlsx'):
    results_list = []
    for problem_config in problem_configs:
        additional_args = None
        if isinstance(problem_config, tuple):
            problem_name, additional_args = problem_config
            pf, results = test(problem_name, n_gen=n_gen,
                               additional_args=additional_args)
        else:
            problem_name = problem_config
            pf, results = test(problem_name, n_gen=n_gen)

        # Skip problems where results are None
        if results[0] is None:
            continue

        # Compute performance indicators
        prepared_data = []
        for i, result in enumerate(results):
            if result and hasattr(result, 'F') and result.F is not None:
                # if i > 0:
                if True:
                    prepared_data.append(result.F[:, :-1])
                else:
                    prepared_data.append(result.F)
            else:
                prepared_data.append(None)

        if all(data is not None for data in prepared_data):
            performance_results = performance_indicators(pf, prepared_data)
            for i, rs in enumerate(performance_results):
                (gd_mean, gd_median), (gd_plus_mean, gd_plus_median), (igd_mean,
                                                                       igd_median), (igd_plus_mean, igd_plus_median) = rs
                result_row = {
                    "Problem": problem_name if additional_args is None else f'{problem_name} {additional_args}',
                    "Algorithm": f"Algorithm {i+1}",
                    "GD Mean": gd_mean,
                    "GD Median": gd_median,
                    "GD+ Mean": gd_plus_mean,
                    "GD+ Median": gd_plus_median,
                    "IGD Mean": igd_mean,
                    "IGD Median": igd_median,
                    "IGD+ Mean": igd_plus_mean,
                    "IGD+ Median": igd_plus_median,
                    "Time": results[i].exec_time if hasattr(results[i], 'exec_time') else np.nan
                }
                results_list.append(result_row)

    # Create DataFrame and export to Excel
    df = pd.DataFrame(results_list)
    df.to_excel(output_file, index=False)
    print(f"Results exported to {output_file}")

    # Create charts for visualizing the results
    # create_charts(df)


# Example usage
problem_configs = [
    # "wrm",
    # "srn",
    # "clutch"
]

problem_dascmop = [f'dascmop{i}' for i in range(1,10)]
for i in range(16,17):
    for p in problem_dascmop:
        problem_configs.append((p, i))
compare_problems_to_excel(problem_configs, n_gen=100,
                          output_file=f'optimization_results_{datetime.now().timestamp()}.xlsx')

In [ ]:
problem_configs = [
    "g7",
    "g8",
    "g9",
    # "mw7",
    # "mw7",
    # "mw9",
    # "mw10",
]
# problem_configs += [f'g{i}' for i in range(1,25)]
compare_problems_to_excel(problem_configs, n_gen=500,
                          output_file=f'optimization_results_{datetime.now().timestamp()}.xlsx')

# Diversity Factor


In [ ]:
import numpy as np
from pymoo.core.problem import Problem
from pymoo.problems import get_problem
from scipy.spatial import cKDTree
from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.operators.crossover.sbx import SimulatedBinaryCrossover as SBX
from pymoo.operators.mutation.pm import PolynomialMutation as PM
from pymoo.operators.sampling.rnd import FloatRandomSampling
from pymoo.optimize import minimize
from pymoo.core.callback import Callback

In [ ]:
from annoy import AnnoyIndex


class DiversityEnhancedProblem(Problem):
    def __init__(self, problem, neighbors=5, trees=10):
        super().__init__(
            n_var=problem.n_var,
            n_obj=problem.n_obj + 1,
            n_constr=problem.n_constr,
            xl=problem.xl,
            xu=problem.xu,
        )
        self.base_problem = problem
        self.neighbors = neighbors
        self.population = []
        self.tree = AnnoyIndex(self.n_var, "manhattan")
        self.tree_cache = {}  # To store diversity values
        self.trees = trees  # Number of trees for Annoy

    def update_population(self, pop):
        self.population = pop.get("X")
        self.tree.unbuild()  # Clear the current tree
        for i, x in enumerate(self.population):
            self.tree.add_item(i, x.tolist())
        self.tree.build(self.trees)
        self.tree_cache = {}  # Clear cache after update

    def calculate_diversity(self, x):
        if len(self.population) > 1:
            distances = self.tree.get_nns_by_vector(
                x, self.neighbors, include_distances=True
            )[1]
            return 1.0 / np.mean(distances)
        return 0

    def _evaluate(self, x, out, *args, **kwargs):
        base_out = {}
        self.base_problem._evaluate(x, base_out, *args, **kwargs)
        f = base_out["F"]
        x = np.atleast_2d(x)

        # Calculate diversity, using cache if available
        diversity = np.array(
            [self.tree_cache.get(
                tuple(xi), self.calculate_diversity(xi)) for xi in x]
        )
        for xi, div in zip(x, diversity):
            self.tree_cache[tuple(xi)] = div  # Update cache

        out["F"] = np.column_stack([f, diversity])


class DiversityCallback(Callback):
    def __init__(self, problem):
        super().__init__()
        self.problem = problem

    def notify(self, algorithm):
        self.problem.update_population(algorithm.pop)


# Original problem from pymoo
original_problem = get_problem("zdt2")

# Enhanced problem with diversity objective
problem = DiversityEnhancedProblem(original_problem, neighbors=10)

# Setup the algorithm
algorithm = NSGA2(
    pop_size=100,
    n_offsprings=10,
    sampling=FloatRandomSampling(),
    crossover=SBX(prob=0.9, eta=15),
    mutation=PM(eta=20),
    eliminate_duplicates=True,
)

# Execute the optimization
res1 = minimize(
    problem,
    algorithm,
    ("n_gen", 10000),
    verbose=True,
    seed=1,
    callback=DiversityCallback(problem),
)

res2 = minimize(
    original_problem,
    algorithm,
    ("n_gen", 2000),
    verbose=False,
    seed=0,
    # callback=DiversityCallback(problem)
)

In [ ]:
print(res1.F.shape, res2.F.shape)

In [ ]:
from visualization.scatter import Scatter

plot = Scatter()
plot.add(res1.F[:, :-1], facecolor="none", edgecolor="red")
plot.add(res2.F, facecolor="none", edgecolor="blue")
plot.show()

In [ ]:
from visualization.scatter import Scatter

plot = Scatter()
plot.add(res1.F, facecolor="none", edgecolor="red")
# plot.add(res2.F, facecolor="none", edgecolor="blue")
plot.show()

In [ ]:
from pymoo.factory import get_performance_indicator

# Assuming 'result' is the output of your optimization algorithm
hv = get_performance_indicator(
    "hv", ref_point=np.array([1.1, 1.1])
)  # Adjust ref_point as needed
hypervolume = hv.calc(res1.F)

print("Hypervolume:", hypervolume)

In [ ]:
from visualization.scatter import Scatter
from annoy import AnnoyIndex
import numpy as np


class DiversityEnhancedProblem2(Problem):
    def __init__(
        self, problem, neighbors=5, trees=10, update_interval=5, change_threshold=0.2
    ):
        super().__init__(
            n_var=problem.n_var,
            n_obj=problem.n_obj + 1,
            n_constr=problem.n_constr,
            xl=problem.xl,
            xu=problem.xu,
        )
        self.base_problem = problem
        self.neighbors = neighbors
        self.population = []
        self.tree = AnnoyIndex(self.n_var, "euclidean")
        self.trees = trees
        self.update_interval = update_interval
        self.change_threshold = change_threshold
        self.generation_count = 0
        self.last_population = None

    def update_population(self, pop):
        self.population = pop.get("X")
        self.generation_count += 1

        # Determine if the tree needs updating
        if (
            self.last_population is None
            or self.generation_count % self.update_interval == 0
            or self.population_has_changed()
        ):
            self.rebuild_tree()
            self.last_population = np.array(self.population.copy())
            print("Tree rebuilt.")

    def population_has_changed(self):
        """Checks if significant changes have occurred in the population"""
        if self.last_population is not None:
            dists = np.linalg.norm(self.last_population - self.population, axis=1)
            significant_changes = np.mean(dists > self.change_threshold)
            # More than 10% of the population has significantly changed
            return significant_changes > 0.1
        return False

    def rebuild_tree(self):
        """Rebuilds the Annoy index"""
        self.tree.unbuild()
        for i, x in enumerate(self.population):
            self.tree.add_item(i, x.tolist())
        self.tree.build(self.trees)

    def calculate_diversity(self, x):
        if len(self.population) > 1:
            distances = self.tree.get_nns_by_vector(
                x, self.neighbors, include_distances=True
            )[1]
            return 1.0 / np.mean(distances)
        return 0

    def _evaluate(self, x, out, *args, **kwargs):
        base_out = {}
        self.base_problem._evaluate(x, base_out, *args, **kwargs)
        f = base_out["F"]
        x = np.atleast_2d(x)

        # Calculate diversity
        diversity = np.array([self.calculate_diversity(xi) for xi in x])
        out["F"] = np.column_stack([f, diversity])


# Original problem from pymoo
original_problem = get_problem("zdt2")

# Enhanced problem with diversity objective
problem2 = DiversityEnhancedProblem2(original_problem, neighbors=10)

# Setup the algorithm
algorithm = NSGA2(
    pop_size=100,
    n_offsprings=10,
    sampling=FloatRandomSampling(),
    crossover=SBX(prob=0.9, eta=15),
    mutation=PM(eta=20),
    eliminate_duplicates=True,
)

# Execute the optimization
res1 = minimize(
    problem2,
    algorithm,
    ("n_gen", 5000),
    verbose=True,
    seed=1,
    callback=DiversityCallback(problem),
)

res2 = minimize(
    original_problem,
    algorithm,
    ("n_gen", 2000),
    verbose=False,
    seed=0,
)


plot = Scatter()
plot.add(res1.F[:, 1:], facecolor="none", edgecolor="red")
plot.add(res2.F, facecolor="none", edgecolor="blue")
plot.show()

In [ ]:
from pymoo.core.problem import Problem
import numpy as np


class ConstraintAsObjectiveProblem(Problem):
    def __init__(self, problem):
        super().__init__(
            n_var=problem.n_var,
            n_obj=problem.n_obj + problem.n_constr,
            n_constr=0,  # No explicit constraints as they are now objectives
            xl=problem.xl,
            xu=problem.xu,
        )
        self.problem = problem

    def _evaluate(self, x, out, *args, **kwargs):
        # Evaluate the original problem
        res = {}
        self.problem._evaluate(x, res)

        # Combine original objectives with constraints as new objectives
        f = res["F"]
        # Constraint violation for g(x) > 0
        g = np.where(res["G"] > 0, res["G"], 0)
        h = np.abs(res["H"])  # Absolute value for equality constraints

        # Combine into a single objective array
        out["F"] = np.column_stack([f, g, h])

In [ ]:
from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.operators.selection.tournament import compare
from pymoo.optimize import minimize
from pymoo.problems import get_problem


class FeasibilityFirstNSGA2(NSGA2):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def _next(self):
        # Overriding the selection process to prioritize feasibility
        def feasibility_first(a, b):
            # Check if either solution is feasible
            is_feasible_a = np.all(self.pop[a].get(
                "F")[self.problem.n_obj:] <= 0)
            is_feasible_b = np.all(self.pop[b].get(
                "F")[self.problem.n_obj:] <= 0)

            if is_feasible_a and not is_feasible_b:
                return a
            elif not is_feasible_a and is_feasible_b:
                return b
            else:
                # If both are feasible or infeasible, fall back to regular comparison
                return compare(
                    a, b, self.pop, self.n_survive, self.rank_key, self.crowding_key
                )

        # Tournament selection modified for feasibility
        mating_pool = self.selection(
            self.pop, self.n_offsprings, feasibility_first)
        off = self.crossover.do(self.problem, self.pop, mating_pool)
        off = self.mutation.do(self.problem, off)
        self.evaluator.eval(self.problem, off)
        self.pop = self.survival.do(
            self.problem, self.pop, off, n_survive=self.pop_size
        )


problem = get_problem("zdt1")
wrapped_problem = ConstraintAsObjectiveProblem(problem)

algorithm = FeasibilityFirstNSGA2(pop_size=100)

res = minimize(wrapped_problem, algorithm, ("n_gen", 100), verbose=True)